config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plants, only: [:index, :new, :show, :create] do
    resources :bookings, only: [:create, :new] # because we need the plant id to create 
  end
  resources :bookings, only: [:index, :show, :update] do # there we dont need the plant id so we dont nest it
    resources :reviews, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  before_validation :set_total_price
  belongs_to :plant
  belongs_to :user
  has_one :review


  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  def set_total_price
    self.total_price = (end_date - start_date).to_i * plant.price
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name, :description, :address],
    using: {
      tsearch: { prefix: true } # <-- tsearch allows partial words, e.g. batm for batman
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true, length: { minimum: 20 }
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plants, dependent: :destroy
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @my_bookings = Booking.where(user: current_user)
    @requested_bookings = Booking.select{|booking| booking.plant.user == current_user}

  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @plant = Plant.find(params[:plant_id])
    @booking.plant = @plant
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def update
      @booking = Booking.find(params[:id])
      @booking.update(booking_params)
      redirect_to bookings_path
  end



  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @plants = Plant.all.first(3)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    query_result

    @markers = @plants.geocoded.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        image_url: helpers.asset_url('plant.png'),
        infoWindow: render_to_string(partial: "info_window", locals: { plant: plant })
      }
    end
  end

  def new
    @plant = Plant.new
  end

  def show
    @plant = Plant.find(params[:id])
    @review = Review.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user
    if @plant.save
      redirect_to plant_path(@plant)
    else
      render :new # jumps to view "new"
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:description, :name, :price, :address, :photo)
  end

  def query_result
    if params[:query].present?
      @plants = Plant.search_by_name(params[:query])
    else
      @plants = Plant.all
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    end
    
    def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to plant_path(@booking.plant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class= "container pt-3">
  <h2 class="mb-3">Your bookings</h2>

  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item-booking">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">My rentals</a>
    </li>
    <li class="nav-item-booking">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">My bookings</a>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

      <% @requested_bookings.each do |booking| %>
      <div class="card-product mb-3">
        <% if booking.plant.photo.attached? %>
          <%= cl_image_tag booking.plant.photo.key %>
        <% else %>
          <%= cl_image_tag("placeholder-plant") %>
        <% end %>
        <div class="card-product-infos w-100">
          <div class="d-flex justify-content-between align-items-end">
            <div>
              <h2><%= booking.plant.name %></h2>
              <p><strong>Start date:</strong><%= booking.start_date %> ------- <strong>End date:</strong><%= booking.end_date %></p>
              <p>Status: <strong><%= booking.status.capitalize %></strong></p>
              <p><strong>Total price:</strong> <%= number_to_currency(booking.total_price) %></p>
            </div>
            <div>
              <% if booking.plant.user == current_user && booking.status == "pending" %>
              <%= link_to "Accept", booking_path(booking, booking: {status: "accepted"}),
                  method: :patch,
                  class: "btn btn-accept"
              %>
              <%= link_to "Decline", booking_path(booking, booking: {status: "declined"}),
                  method: :patch,
                  class: "btn btn-decline"
              %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <% @my_bookings.each do |booking| %>
          <div class="card-product mb-3">
            <% if booking.plant.photo.attached? %>
              <%= cl_image_tag booking.plant.photo.key %>
            <% else %>
              <%= cl_image_tag("placeholder-plant") %>
            <% end %>
            <div class="card-product-infos w-100 d-flex justify-content-between align-items-end">
              <div>
                <h2><%= booking.plant.name %></h2>
                <p><strong>Start date:</strong><%= booking.start_date %> ------- <strong>End date:</strong><%= booking.end_date %></p>
                <p>Status: <strong><%= booking.status.capitalize %></strong></p>
                <p><strong>Total price:</strong> <%= number_to_currency(booking.total_price) %></p>
              </div>
              
              <%= link_to 'Leave a review', new_booking_review_path(booking),
                class: "btn-review" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container col-9 pt-3">
  <div class="row mt-3 plant-show-card">
        <div class="col-6 pl-0">
          <% if @plant.photo.attached? %>
            <%= cl_image_tag @plant.photo.key, width: 462, height: 400, crop: :fill, class: "w-100" %>
         <% else %>
            <%= cl_image_tag("placeholder-plant", width: 462, height: 400, crop: :fill, class: "w-100") %>
         <% end %>
        </div>
        <div class="col-6 p-3 mt-3 d-flex flex-column justify-content-around">
          <div>
            <h1> <%= @plant.name %> </h1>
              <%= simple_form_for [@plant, @booking] do |f| %>
              <%= f.input :start_date, as: :string, input_html: {id: "start_date"} %>
              <%= f.input :end_date, as: :string, input_html: {id: "end_date"} %>
               <%= f.submit "Book",  class:"btn-main btn-block" %>
          </div>
          <div class="row align-items-center justify-content-between">
            <div class="col-6">
              <h5><%= number_to_currency(@plant.price) %> / day</h5>
            </div>
            <div class="col-6">
            </div>
          </div>
          <% end %>
        </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container pt-3">
  <h2>Congratulations on booking <%= @booking.plant.name %></h2>
  <div class="container pl-0 pt-3">
    <div class="card-product">
      <% if @booking.plant.photo.attached? %>
          <%= cl_image_tag @booking.plant.photo.key %>
        <% else %>
          <%= cl_image_tag("placeholder-plant") %>
        <% end %>
      <div class="card-product-infos">
        <h2><%= @booking.plant.name %></h2>
        <p><strong>Start date:</strong><%= @booking.start_date %> ------- <strong>End date:</strong><%= @booking.end_date %></p>
        <p>Status: <strong><%= @booking.status.capitalize %></strong></p>
        <p><strong>Total price:</strong> <%= number_to_currency(@booking.total_price) %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantLord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="https://res.cloudinary.com/dwl79z56q/image/upload/v1607081588/PlantLord/Plantlord-logo-icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body>
      <%= render 'shared/flashes' %>
      <%= render 'shared/navbar' %>
      <div class="spacing">
      <%= yield %>
      </div>
      <%= render 'shared/footer' %>
      <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex align-items-center" style="background-image: url(https://images.unsplash.com/photo-1457282168619-2383c79b278d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1508&q=80);">
  
  <div class="container">

    <h1><strong>Add some green to your space</strong></h1>
    <h3>Search something you will love</h3>
    <div class="btn-padding">
      <%= link_to "Explore our plants", plants_path, class:"btn-main" %>
    </div>
  </div>
</div>

<div class= "container">


  <h3 class="my-3"> Top plants </h3>

   <div class="row">
      <% @plants.each do |plant| %>
        <div class="col-4">
          <%= link_to plant_path(plant), class: "plant-card-link" do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path plant.photo.key, crop: :fit %>)">
              <%= plant.name.capitalize %>
              <h2 class="card-plant-pricing"><%= number_to_currency(plant.price, precision: 0) %></h2>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

</div>

app/views/plants/_info_window.html.erb
<div style="display: flex">

  <div >
    <h2><%= plant.name %></h2>
    <p><%= plant.address %></p>
  </div>
  <div class="info-window-img">
    <% if plant.photo.attached? %>
                <%= cl_image_tag plant.photo.key, height: 100, width: 100, crop: :fit %>
    <% else %>
                <%= cl_image_tag("placeholder-plant", height: 100, width: 100, crop: :fit) %>
              <% end %>
  </div>
</div>

app/views/plants/index.html.erb
<div id="map"
    style="width: 100%; height: 300px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

<div class= "container">
  <div class="index-header">
    <h3 class="my-3"> There's a lot to discover here </h3>
  </div>

  <div class="row">
    <% @plants.each do |plant| %>
      <div class="col-4">
        <%= link_to plant_path(plant), class: "plant-card-link" do %>
          <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path plant.photo.key, crop: :fit %>)">
            <%= plant.name.capitalize %>
            <h2 class="card-plant-pricing"><%= number_to_currency(plant.price, precision: 0) %></h2>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>








</div>

app/views/plants/new.html.erb
<div class="container mt-4 col-6 pt-3">
  <h2>Create your plant</h2>
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [@user, @plant] do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Submit me",  class:"btn-main" %>
      <% end %>
    </div>
    <div class="col-6">
      <img src="https://cdn.shopify.com/s/files/1/0013/3529/6118/products/Wythe-40-2970.040-WH_Bird-of-Paradise-14.jpg?v=1604354745" width="400" height="500">
    </div>
  </div>

</div>

app/views/plants/show.html.erb
<div class="container col-9 pt-3">
  <div class="row plant-show-card">
        <div class="col-6 pl-0">
          <% if @plant.photo.attached? %>
            <%= cl_image_tag @plant.photo.key, width: 462, height: 400, crop: :fill, class: "w-100 h-100" %>
         <% else %>
            <%= cl_image_tag("placeholder-plant", width: 462, height: 400, crop: :fill, class: "w-100 h-100") %>
         <% end %>
        </div>
        <div class="d-flex flex-column justify-content-around col-6 p-3 mt-3">
          <div>
            <h1> <%= @plant.name %> </h1>
            <h5>About this plant:</h5>
            <div class="container mt-3 pl-0">
              <p><i class="fas fa-tint icon"></i> Every <strong>3</strong> days</p>
              <p><i class="fas fa-sun icon"></i> Outdoor </p>
              <p><i class="fas fa-ruler icon"></i></i> 30 cms</p>
            </div>
          </div>
          <div class="row mr-0 mt-5 p-0">
            <div class="col-6">
              <h5><%= number_to_currency(@plant.price) %>/ day</h5>
            </div>
            <div class="col-6 text-right">
              <% if @plant.user != current_user %>
                <%= link_to "Book now", new_plant_booking_path(@plant), class: "btn-main" %>
              <% end %>
            </div>
          </div>
        </div>
  </div>
  <div class="row mt-3">
    <div class="col-6 p-0 pr-3">
      <div class="card text-left align-center">
        <div class="card-header m-0">
          <h4>Description</h4>
        </div>
        <div class="card-body">
          <p class="card-text"><%= @plant.description %></p>
        </div>
      </div>

    </div>
    <div class="col-6 p-0">
      <div class="card">
        <div class="card-header">
          <h4>Reviews</h4>
        </div>
        <% @plant.reviews.each do |review| %>
          <div class="card-body">
            <h5 class="card-title">
              <strong>
                <%= review.booking.user.email.split("@")[0].capitalize %></strong>'s review:
            </h5>
            <% review.rating.times do%>
              <i class="fas fa-star icon"></i>
            <% end %>

            <% (5 - review.rating).times do %>
              <i class="far fa-star icon"></i>
            <% end %>
            <p class="card-text"> <%= review.content.capitalize %></p>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container mt-4 col-6">
  <h2>Leave a Review</h2>
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content%>
        <%= f.submit "Submit me",  class:"btn-main" %>
      <% end %>
    </div>
    <div class="col-6">
      <%# <img src="https://cdn.shopify.com/s/files/1/0013/3529/6118/products/Wythe-40-2970.040-WH_Bird-of-Paradise-14.jpg?v=1604354745" width="350" height="250"> %>
      <%= cl_image_tag @booking.plant.photo.key, width: 462, height: 400, crop: :fill, class: "w-100 h-100" %>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container pt-1 pb-2 mb-1">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dwl79z56q/image/upload/v1607076721/PlantLord/Plantlord-logo.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="search-container-navbar">
      <div>
        <div class="search-bar"><%= form_tag plants_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find your plant" %>
            <%= button_tag(type: "submit", class: "btn-main btn-search") do %>
                <i class="fas fa-search"></i>
            <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars3.githubusercontent.com/u/72553836?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Add a plant", new_plant_path, class: "dropdown-item" %>
              <hr>
              <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>